-- Deprecated.
--
-- The canonical schema for this project lives in:
--   1. 0001_initial_schema.sql
--   2. 0002_schema_unification.sql
--
-- Do not apply this file directly. It previously provisioned an older,
-- incompatible schema using jobs/challenges/submissions and question /
-- ideal_answer columns, which no longer match the application.
