-- Seed questions (from user's list)
-- Note: run after initial.sql

INSERT INTO questions (category, question, ideal_answer, level) VALUES
('React','Difference between useMemo and useCallback?','useMemo caches a value; useCallback caches a function instance to prevent re-renders of memoized child components.','medium'),
('React','How does the Virtual DOM improve performance?','It calculates the minimum number of changes (diffing) and batches updates to the real DOM to avoid expensive layout reflows.','easy'),
('React','What is the "Rules of Hooks"?','Hooks must be called at the top level (not inside loops/conditions) and only from React functions.','easy'),
('React','Explain the "Prop Drilling" problem.','Passing data through multiple layers of components that don\'t need it. Solved by Context API or Redux.','easy'),
('React','What are "Controlled Components"?','Components where the form data is handled by the React state, not the DOM itself.','easy'),
('JS','Difference between == and ===?','Use === for strict equality (no type coercion); == performs type coercion.','easy'),
('JS','What is "Hoisting"?','JS moves declarations (not initializations) to the top of the scope. var is hoisted; let/const are in the "Temporal Dead Zone."','easy'),
('JS','Explain "Closures."','A function that remembers the variables from its outer scope even after the outer function has finished executing.','easy'),
('JS','What is a "Promise"?','An object representing the eventual completion (or failure) of an asynchronous operation.','easy'),
('JS','Explain prototypal inheritance.','Objects in JS inherit properties and methods from other objects via a prototype chain.','medium'),
('Node.js','How does Node handle concurrency?','Via the Event Loop. It uses a single-threaded non-blocking I/O model.','easy'),
('Node.js','What is the purpose of package-lock.json?','It locks the exact versions of dependencies to ensure consistent installs across different environments.','easy'),
('Node.js','Explain "Middleware" in Express.','Functions that have access to req, res, and next(). They execute in order during the request-response cycle.','easy'),
('Node.js','Difference between process.nextTick() and setImmediate()?','nextTick fires immediately after the current operation; setImmediate fires on the next turn of the event loop.','medium'),
('Node.js','How do you handle CPU-intensive tasks in Node?','Use Worker Threads or offload to a separate microservice/Lambda.','medium'),
('TS','What is an Interface vs a Type?','Both define shapes; Interfaces are better for merging (declaration merging), Types are better for unions and aliases.','medium'),
('TS','What does unknown mean?','A type-safe version of any. You must perform type-checking before performing operations on an unknown value.','easy'),
('TS','What are "Generics"?','A way to create reusable components/functions that work with a variety of types rather than a single one.','easy'),
('TS','What is "Type Narrowing"?','Using logic (like typeof or instanceof) to refine a broad type into a more specific one.','medium'),
('TS','Explain readonly.','A keyword that prevents a property from being modified after it is initialized.','easy'),
('AI Skills','What is "Prompt Engineering"?','The process of structured input design (context, task, constraints) to get accurate outputs from an LLM.','medium'),
('AI Skills','How do you prevent AI Hallucinations?','Using RAG (Retrieval Augmented Generation), temperature control, and few-shot prompting with valid examples.','medium'),
('AI Skills','What is an "Agentic Workflow"?','A system where an AI agent can use "tools" (APIs, calculators) to complete multi-step tasks autonomously.','medium'),
('AI Skills','What are "Tokens" in LLMs?','The basic units of text (sub-words) that an LLM processes. Token limits dictate how much context an AI can "remember."','easy'),
('HTML/CSS','What is the "Box Model"?','The layout structure consisting of Content, Padding, Border, and Margin.','easy'),
('HTML/CSS','Difference between flexbox and grid?','Flexbox is 1D (rows OR columns); Grid is 2D (rows AND columns).','easy'),
('HTML/CSS','What are "Semantic HTML" tags?','Tags like <header>, <main>, and <footer> that provide meaning to the browser and screen readers.','easy'),
('Architecture','What is a "Microservices" architecture?','Breaking a large app into small, independent services that communicate over APIs (REST/gRPC).','medium'),
('Architecture','Explain "Serverless" (AWS Lambda).','Computing where the cloud provider manages the server; you only pay for the execution time of your code.','easy'),
('Architecture','What is "CORS"?','Cross-Origin Resource Sharing—a security feature that restricts web pages from making requests to a different domain.','easy');

-- Seed snippet challenges
INSERT INTO snippets (title, code, explanation, language) VALUES
('[] == ![]','console.log([] == ![]);','true. (Coercion: ![] is false, [] is coerced to 0, false is coerced to 0).','javascript'),
('push on const array','const x = [1,2]; x.push(3);','No. const prevents re-assignment of the variable, but the object/array itself is still mutable.','javascript'),
('typeof NaN','console.log(typeof NaN);','"number". (NaN stands for Not-a-Number, but its type is numeric).','javascript'),
('setTimeout order','setTimeout(()=>console.log(1),0); console.log(2);','2, 1. (Synchronous code runs before the event loop task).','javascript'),
('ASI return newline','function a() { return { b: 1 } }\nfunction b() { return \n {b:1} }','Second returns undefined due to Automatic Semicolon Insertion (ASI).','javascript'),
('array sort default','[1, 2, 11].sort()','[1, 11, 2]. (Sort converts to strings; "11" comes before "2").','javascript'),
('object key stringified','const a = {}; const b = {key:\'b\'}; a[b] = 123;','a[b] becomes 123; object keys are stringified to "[object Object]".','javascript'),
('implicit global in function','(function(){ var a = b = 3; })();','b becomes a global variable because it lacks a keyword.','javascript'),
('floating point','0.1 + 0.2 === 0.3','false. (Floating point precision leads to 0.30000000000000004).','javascript'),
('type intersection','type T = string & number','never. (A value cannot be both a string and a number).','typescript'),
('Object.freeze','const user = { name: "A" }; Object.freeze(user); user.name = "B";','user.name remains "A". (Freeze makes it immutable).','javascript'),
('post-increment','let x = 1; let y = x++;','y is 1. (Post-increment returns value before adding).','javascript'),
('1<2<3','console.log(1 < 2 < 3)','true. (1 < 2 is true (1), 1 < 3 is true).','javascript'),
('3<2<1','console.log(3 < 2 < 1)','true. (3 < 2 is false (0), 0 < 1 is true).','javascript'),
('useEffect deps object','React.useEffect(() => { /*...*/ }, [{}]);','Risk: infinite loop because {} is a new reference every render.','react'),
('batched state updates','const [val, setVal] = useState(0); setVal(val + 1); setVal(val + 1);','Final val: 1. (State updates are batched; both use the same initial val).','react'),
('interface merging','interface A { x: number }; interface A { y: number };','A has both x and y. (Interface merging).','typescript'),
('true && "Hello"','(true && "Hello")','"Hello".','javascript'),
('false && "Hello"','(false && "Hello")','false.','javascript'),
('double bang empty string','!!""','false. (Empty string is falsy).','javascript'),
('1 + "1"','console.log(1 + "1")','"11".','javascript'),
('1 - "1"','console.log(1 - "1")','0. (Minus forces numeric conversion).','javascript'),
('fetch 404 catch','fetch().then(r => r.json()).catch(e => ...)','No. fetch only rejects on network failure, not HTTP errors.','javascript'),
('typeof async','const x = async () => 1;','typeof x() is Promise. (Async functions always return promises).','javascript'),
('css margin shorthand','div { margin: 10px 5px; }','Top/Bottom margin: 10px.','css'),
('TS syntax error','TS: function log(x: string number) { console.log(x.length) }','Syntax error: missing ":" between parameter name and type or comma.','typescript'),
('array length after sparse assign','const arr = [1, 2, 3]; arr[10] = 99;','arr.length is 11. (Creates \"holes\" in the array).','javascript'),
('Array.isArray null','Array.isArray(null)','false.','javascript'),
('module.exports override','Node: module.exports = { a: 1 }; exports.b = 2;','Result of require: { a: 1 }. (module.exports overrides exports).','javascript');
